POST http://127.0.0.1:8080/MyService/MySEntity
Content-Type: application/json

{
    "ID": "k3943c14-7440-4f2f-bfb0-1aa93f7accbd",
    "name": "First Entity",
    "age": 9,
    "isGerman": true
}

###
GET http://127.0.0.1:8080/MyService/MySEntity?$filter=age gte 8